global using Xunit;
global using FluentAssertions;
global using CleanArchi_ExoFinal.Handlers.CommandHandlers;
global using CleanArchi_ExoFinal.Infrastructure.Repositories;
global using CleanArchi_ExoFinal.Application;
global using CleanArchi_ExoFinal.Domain;
global using CleanArchi_ExoFinal.Application.Handlers.QueryHandlers;
global using CleanArchi_ExoFinal;
global using CleanArchi_ExoFinal.Application.Handlers.CommandHandlers;